# `Profile` - gtp-engine-to-nngs が利用する区画。 エンジンは gtp-engine-to-nngs からの `Name`, `Pass` の要求があったとき応答する必要があります
[Profile]

# 対局者名（アカウント名）
# Only A-Z a-z 0-9
# Names may be at most 10 characters long
Name = 'kifuwara_w'

Pass = '' # your password (any)

# `Engine` - GTPエンジンが任意に利用する区画。NNGSや gtp-engine-to-nngs はここは見ません
[Engine]

# Komi - コミ☆（＾～＾）
Komi = 6.5

# BoardSize - 何路盤。
BoardSize = 9

# MaxMoves - 最大手数。
MaxMoves = 1000

# BoardData - 盤
# '.' - 空点
# 'x' - 黒石
# 'o' - 白石
# '+' - 枠
# ' ' - 半角空白は無視します
BoardData = '''
	+ + + + + + + + + + +
	+ o x x . x . . . . +
	+ o o x x . x o . . +
	+ o . o x o o x x . +
	+ . o o o x x x . . +
	+ . . . o x o x . . +
	+ . . o . o o x . . +
	+ . . . . o x x . . +
	+ . . . . o o x . . +
	+ . . . . . o x . . +
	+ + + + + + + + + + +
'''
